// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License.

// <auto-generated/>

#nullable disable

namespace Zuuse.Lifecycle.Client.Models
{
    /// <summary> The AssetReference. </summary>
    public partial class AssetReference
    {
        /// <summary> Initializes a new instance of AssetReference. </summary>
        public AssetReference()
        {
        }

        /// <summary> Initializes a new instance of AssetReference. </summary>
        /// <param name="id"> . </param>
        /// <param name="name"> . </param>
        /// <param name="isPhysical"> . </param>
        /// <param name="isActive"> . </param>
        internal AssetReference(string id, string name, bool? isPhysical, bool? isActive)
        {
            Id = id;
            Name = name;
            IsPhysical = isPhysical;
            IsActive = isActive;
        }

        public string Id { get; set; }
        public string Name { get; set; }
        public bool? IsPhysical { get; set; }
        public bool? IsActive { get; set; }
    }
}
