// <auto-generated>
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace Zuuse.Lifecycle.Client.Models
{
    using Newtonsoft.Json;
    using System.Linq;

    public partial class AssetReference
    {
        /// <summary>
        /// Initializes a new instance of the AssetReference class.
        /// </summary>
        public AssetReference()
        {
            CustomInit();
        }

        /// <summary>
        /// Initializes a new instance of the AssetReference class.
        /// </summary>
        public AssetReference(string id = default(string), string name = default(string), bool? isPhysical = default(bool?), bool? isActive = default(bool?))
        {
            Id = id;
            Name = name;
            IsPhysical = isPhysical;
            IsActive = isActive;
            CustomInit();
        }

        /// <summary>
        /// An initialization method that performs custom operations like setting defaults
        /// </summary>
        partial void CustomInit();

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "Id")]
        public string Id { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "Name")]
        public string Name { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "IsPhysical")]
        public bool? IsPhysical { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "IsActive")]
        public bool? IsActive { get; set; }

    }
}
