// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License.

// <auto-generated/>

#nullable disable

namespace Zuuse.Lifecycle.Client.Models
{
    /// <summary> The BaselineScenarioDetails. </summary>
    public partial class BaselineScenarioDetails
    {
        /// <summary> Initializes a new instance of BaselineScenarioDetails. </summary>
        internal BaselineScenarioDetails()
        {
        }

        /// <summary> Initializes a new instance of BaselineScenarioDetails. </summary>
        /// <param name="id"> . </param>
        /// <param name="displayName"> . </param>
        /// <param name="baselineId"> . </param>
        /// <param name="isPublished"> . </param>
        /// <param name="isActive"> . </param>
        internal BaselineScenarioDetails(string id, string displayName, string baselineId, bool? isPublished, bool? isActive)
        {
            Id = id;
            DisplayName = displayName;
            BaselineId = baselineId;
            IsPublished = isPublished;
            IsActive = isActive;
        }

        public string Id { get; }
        public string DisplayName { get; }
        public string BaselineId { get; }
        public bool? IsPublished { get; }
        public bool? IsActive { get; }
    }
}
