// <auto-generated>
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace Zuuse.Lifecycle.Client.Models
{
    using Newtonsoft.Json;
    using System.Collections;
    using System.Collections.Generic;
    using System.Linq;

    public partial class BaselineInterventions
    {
        /// <summary>
        /// Initializes a new instance of the BaselineInterventions class.
        /// </summary>
        public BaselineInterventions()
        {
            CustomInit();
        }

        /// <summary>
        /// Initializes a new instance of the BaselineInterventions class.
        /// </summary>
        public BaselineInterventions(string baselineId = default(string), string baselineName = default(string), int? startYear = default(int?), int? years = default(int?), System.DateTime? runDate = default(System.DateTime?), TaxonomyNames taxonomyNames = default(TaxonomyNames), IList<InterventionSetWithTaxonomy> interventionSets = default(IList<InterventionSetWithTaxonomy>))
        {
            BaselineId = baselineId;
            BaselineName = baselineName;
            StartYear = startYear;
            Years = years;
            RunDate = runDate;
            TaxonomyNames = taxonomyNames;
            InterventionSets = interventionSets;
            CustomInit();
        }

        /// <summary>
        /// An initialization method that performs custom operations like setting defaults
        /// </summary>
        partial void CustomInit();

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "BaselineId")]
        public string BaselineId { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "BaselineName")]
        public string BaselineName { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "StartYear")]
        public int? StartYear { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "Years")]
        public int? Years { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "RunDate")]
        public System.DateTime? RunDate { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "TaxonomyNames")]
        public TaxonomyNames TaxonomyNames { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "InterventionSets")]
        public IList<InterventionSetWithTaxonomy> InterventionSets { get; set; }

    }
}
