// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License.

// <auto-generated/>

#nullable disable

using System.Collections.Generic;
using Azure.Core;

namespace Zuuse.Lifecycle.Client.Models
{
    /// <summary> The BaselineScenarioSummary. </summary>
    public partial class BaselineScenarioSummary
    {
        /// <summary> Initializes a new instance of BaselineScenarioSummary. </summary>
        internal BaselineScenarioSummary()
        {
            AdditionalAssetDataPoints = new ChangeTrackingList<BaselineScenarioSummaryDataPoints>();
            TaxonomyBreakdownSummaries = new ChangeTrackingList<TaxonomyBreakdownSummary>();
        }

        /// <summary> Initializes a new instance of BaselineScenarioSummary. </summary>
        /// <param name="startYear"> . </param>
        /// <param name="totalAssets"> . </param>
        /// <param name="filteredAssets"> . </param>
        /// <param name="totalAssetsAtRisk"> . </param>
        /// <param name="additionalAssetsAtRisk"> . </param>
        /// <param name="maxInterventionAtTopLevel"> . </param>
        /// <param name="location"> . </param>
        /// <param name="function"> . </param>
        /// <param name="additionalAssetDataPoints"> . </param>
        /// <param name="taxonomyBreakdownSummaries"> . </param>
        internal BaselineScenarioSummary(int? startYear, int? totalAssets, int? filteredAssets, int? totalAssetsAtRisk, int? additionalAssetsAtRisk, double? maxInterventionAtTopLevel, TaxonomyPosition location, TaxonomyPosition function, IReadOnlyList<BaselineScenarioSummaryDataPoints> additionalAssetDataPoints, IReadOnlyList<TaxonomyBreakdownSummary> taxonomyBreakdownSummaries)
        {
            StartYear = startYear;
            TotalAssets = totalAssets;
            FilteredAssets = filteredAssets;
            TotalAssetsAtRisk = totalAssetsAtRisk;
            AdditionalAssetsAtRisk = additionalAssetsAtRisk;
            MaxInterventionAtTopLevel = maxInterventionAtTopLevel;
            Location = location;
            Function = function;
            AdditionalAssetDataPoints = additionalAssetDataPoints;
            TaxonomyBreakdownSummaries = taxonomyBreakdownSummaries;
        }

        public int? StartYear { get; }
        public int? TotalAssets { get; }
        public int? FilteredAssets { get; }
        public int? TotalAssetsAtRisk { get; }
        public int? AdditionalAssetsAtRisk { get; }
        public double? MaxInterventionAtTopLevel { get; }
        public TaxonomyPosition Location { get; }
        public TaxonomyPosition Function { get; }
        public IReadOnlyList<BaselineScenarioSummaryDataPoints> AdditionalAssetDataPoints { get; }
        public IReadOnlyList<TaxonomyBreakdownSummary> TaxonomyBreakdownSummaries { get; }
    }
}
