// <auto-generated>
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace Zuuse.Lifecycle.Client.Models
{
    using Newtonsoft.Json;
    using System.Collections;
    using System.Collections.Generic;
    using System.Linq;

    public partial class BaselineScenarioSummary
    {
        /// <summary>
        /// Initializes a new instance of the BaselineScenarioSummary class.
        /// </summary>
        public BaselineScenarioSummary()
        {
            CustomInit();
        }

        /// <summary>
        /// Initializes a new instance of the BaselineScenarioSummary class.
        /// </summary>
        public BaselineScenarioSummary(int? startYear = default(int?), int? totalAssets = default(int?), int? filteredAssets = default(int?), int? totalAssetsAtRisk = default(int?), int? additionalAssetsAtRisk = default(int?), double? maxInterventionAtTopLevel = default(double?), TaxonomyPosition location = default(TaxonomyPosition), TaxonomyPosition function = default(TaxonomyPosition), IList<BaselineScenarioSummaryDataPoints> additionalAssetDataPoints = default(IList<BaselineScenarioSummaryDataPoints>), IList<TaxonomyBreakdownSummary> taxonomyBreakdownSummaries = default(IList<TaxonomyBreakdownSummary>))
        {
            StartYear = startYear;
            TotalAssets = totalAssets;
            FilteredAssets = filteredAssets;
            TotalAssetsAtRisk = totalAssetsAtRisk;
            AdditionalAssetsAtRisk = additionalAssetsAtRisk;
            MaxInterventionAtTopLevel = maxInterventionAtTopLevel;
            Location = location;
            Function = function;
            AdditionalAssetDataPoints = additionalAssetDataPoints;
            TaxonomyBreakdownSummaries = taxonomyBreakdownSummaries;
            CustomInit();
        }

        /// <summary>
        /// An initialization method that performs custom operations like setting defaults
        /// </summary>
        partial void CustomInit();

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "StartYear")]
        public int? StartYear { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "TotalAssets")]
        public int? TotalAssets { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "FilteredAssets")]
        public int? FilteredAssets { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "TotalAssetsAtRisk")]
        public int? TotalAssetsAtRisk { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "AdditionalAssetsAtRisk")]
        public int? AdditionalAssetsAtRisk { get; private set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "MaxInterventionAtTopLevel")]
        public double? MaxInterventionAtTopLevel { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "Location")]
        public TaxonomyPosition Location { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "Function")]
        public TaxonomyPosition Function { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "AdditionalAssetDataPoints")]
        public IList<BaselineScenarioSummaryDataPoints> AdditionalAssetDataPoints { get; private set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "TaxonomyBreakdownSummaries")]
        public IList<TaxonomyBreakdownSummary> TaxonomyBreakdownSummaries { get; private set; }

    }
}
