// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License.

// <auto-generated/>

#nullable disable

using System.Collections.Generic;
using Azure.Core;

namespace Zuuse.Lifecycle.Client.Models
{
    /// <summary> The BaselineSummary. </summary>
    public partial class BaselineSummary
    {
        /// <summary> Initializes a new instance of BaselineSummary. </summary>
        internal BaselineSummary()
        {
            Interventions = new ChangeTrackingList<double>();
            DrillDownLocations = new ChangeTrackingList<TaxonomySummary>();
            DrillDownFunctions = new ChangeTrackingList<TaxonomySummary>();
        }

        /// <summary> Initializes a new instance of BaselineSummary. </summary>
        /// <param name="baselineId"> . </param>
        /// <param name="name"> . </param>
        /// <param name="startYear"> . </param>
        /// <param name="years"> . </param>
        /// <param name="maxInterventionAtTopLevel"> . </param>
        /// <param name="interventions"> . </param>
        /// <param name="location"> . </param>
        /// <param name="function"> . </param>
        /// <param name="drillDownLocations"> . </param>
        /// <param name="drillDownFunctions"> . </param>
        internal BaselineSummary(string baselineId, string name, int? startYear, int? years, double? maxInterventionAtTopLevel, IReadOnlyList<double> interventions, TaxonomyPosition location, TaxonomyPosition function, IReadOnlyList<TaxonomySummary> drillDownLocations, IReadOnlyList<TaxonomySummary> drillDownFunctions)
        {
            BaselineId = baselineId;
            Name = name;
            StartYear = startYear;
            Years = years;
            MaxInterventionAtTopLevel = maxInterventionAtTopLevel;
            Interventions = interventions;
            Location = location;
            Function = function;
            DrillDownLocations = drillDownLocations;
            DrillDownFunctions = drillDownFunctions;
        }

        public string BaselineId { get; }
        public string Name { get; }
        public int? StartYear { get; }
        public int? Years { get; }
        public double? MaxInterventionAtTopLevel { get; }
        public IReadOnlyList<double> Interventions { get; }
        public TaxonomyPosition Location { get; }
        public TaxonomyPosition Function { get; }
        public IReadOnlyList<TaxonomySummary> DrillDownLocations { get; }
        public IReadOnlyList<TaxonomySummary> DrillDownFunctions { get; }
    }
}
