// <auto-generated>
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace Zuuse.Lifecycle.Client.Models
{
    using Newtonsoft.Json;
    using System.Collections;
    using System.Collections.Generic;
    using System.Linq;

    public partial class BaselineSummary
    {
        /// <summary>
        /// Initializes a new instance of the BaselineSummary class.
        /// </summary>
        public BaselineSummary()
        {
            CustomInit();
        }

        /// <summary>
        /// Initializes a new instance of the BaselineSummary class.
        /// </summary>
        public BaselineSummary(string baselineId = default(string), string name = default(string), int? startYear = default(int?), int? years = default(int?), double? maxInterventionAtTopLevel = default(double?), IList<double?> interventions = default(IList<double?>), TaxonomyPosition location = default(TaxonomyPosition), TaxonomyPosition function = default(TaxonomyPosition), IList<TaxonomySummary> drillDownLocations = default(IList<TaxonomySummary>), IList<TaxonomySummary> drillDownFunctions = default(IList<TaxonomySummary>))
        {
            BaselineId = baselineId;
            Name = name;
            StartYear = startYear;
            Years = years;
            MaxInterventionAtTopLevel = maxInterventionAtTopLevel;
            Interventions = interventions;
            Location = location;
            Function = function;
            DrillDownLocations = drillDownLocations;
            DrillDownFunctions = drillDownFunctions;
            CustomInit();
        }

        /// <summary>
        /// An initialization method that performs custom operations like setting defaults
        /// </summary>
        partial void CustomInit();

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "BaselineId")]
        public string BaselineId { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "Name")]
        public string Name { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "StartYear")]
        public int? StartYear { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "Years")]
        public int? Years { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "MaxInterventionAtTopLevel")]
        public double? MaxInterventionAtTopLevel { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "Interventions")]
        public IList<double?> Interventions { get; private set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "Location")]
        public TaxonomyPosition Location { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "Function")]
        public TaxonomyPosition Function { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "DrillDownLocations")]
        public IList<TaxonomySummary> DrillDownLocations { get; private set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "DrillDownFunctions")]
        public IList<TaxonomySummary> DrillDownFunctions { get; private set; }

    }
}
