// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License.

// <auto-generated/>

#nullable disable

using System;
using System.Collections.Generic;
using Azure.Core;

namespace Zuuse.Lifecycle.Client.Models
{
    /// <summary> The BaselineInterventions. </summary>
    public partial class BaselineInterventions
    {
        /// <summary> Initializes a new instance of BaselineInterventions. </summary>
        internal BaselineInterventions()
        {
            AttributeNames = new ChangeTrackingList<string>();
            MeasureNames = new ChangeTrackingList<string>();
            InterventionSets = new ChangeTrackingList<InterventionSetWithTaxonomy>();
        }

        /// <summary> Initializes a new instance of BaselineInterventions. </summary>
        /// <param name="baselineId"> . </param>
        /// <param name="baselineName"> . </param>
        /// <param name="startYear"> . </param>
        /// <param name="years"> . </param>
        /// <param name="runDate"> . </param>
        /// <param name="taxonomyNames"> . </param>
        /// <param name="attributeNames"> . </param>
        /// <param name="measureNames"> . </param>
        /// <param name="interventionSets"> . </param>
        internal BaselineInterventions(string baselineId, string baselineName, int? startYear, int? years, DateTimeOffset? runDate, TaxonomyNames taxonomyNames, IReadOnlyList<string> attributeNames, IReadOnlyList<string> measureNames, IReadOnlyList<InterventionSetWithTaxonomy> interventionSets)
        {
            BaselineId = baselineId;
            BaselineName = baselineName;
            StartYear = startYear;
            Years = years;
            RunDate = runDate;
            TaxonomyNames = taxonomyNames;
            AttributeNames = attributeNames;
            MeasureNames = measureNames;
            InterventionSets = interventionSets;
        }

        public string BaselineId { get; }
        public string BaselineName { get; }
        public int? StartYear { get; }
        public int? Years { get; }
        public DateTimeOffset? RunDate { get; }
        public TaxonomyNames TaxonomyNames { get; }
        public IReadOnlyList<string> AttributeNames { get; }
        public IReadOnlyList<string> MeasureNames { get; }
        public IReadOnlyList<InterventionSetWithTaxonomy> InterventionSets { get; }
    }
}
