// <auto-generated>
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace Zuuse.Lifecycle.Client.Models
{
    using Newtonsoft.Json;
    using System.Linq;

    public partial class Deferral
    {
        /// <summary>
        /// Initializes a new instance of the Deferral class.
        /// </summary>
        public Deferral()
        {
            CustomInit();
        }

        /// <summary>
        /// Initializes a new instance of the Deferral class.
        /// </summary>
        public Deferral(TaxonomyPosition location = default(TaxonomyPosition), TaxonomyPosition function = default(TaxonomyPosition), int? yearsDeferred = default(int?))
        {
            Location = location;
            Function = function;
            YearsDeferred = yearsDeferred;
            CustomInit();
        }

        /// <summary>
        /// An initialization method that performs custom operations like setting defaults
        /// </summary>
        partial void CustomInit();

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "Location")]
        public TaxonomyPosition Location { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "Function")]
        public TaxonomyPosition Function { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "YearsDeferred")]
        public int? YearsDeferred { get; set; }

    }
}
