// <auto-generated>
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace Zuuse.Lifecycle.Client.Models
{
    using Newtonsoft.Json;
    using System.Collections;
    using System.Collections.Generic;
    using System.Linq;

    public partial class Entity
    {
        /// <summary>
        /// Initializes a new instance of the Entity class.
        /// </summary>
        public Entity()
        {
            CustomInit();
        }

        /// <summary>
        /// Initializes a new instance of the Entity class.
        /// </summary>
        public Entity(IList<Value> values = default(IList<Value>), System.DateTime? createdDate = default(System.DateTime?), string createdBy = default(string), bool? isActive = default(bool?), string id = default(string), System.DateTime? versionDate = default(System.DateTime?), string versionBy = default(string), bool? locked = default(bool?), string templateReference = default(string), AssetReference owner = default(AssetReference), IList<Relation> relatedEntities = default(IList<Relation>))
        {
            Values = values;
            CreatedDate = createdDate;
            CreatedBy = createdBy;
            IsActive = isActive;
            Id = id;
            VersionDate = versionDate;
            VersionBy = versionBy;
            Locked = locked;
            TemplateReference = templateReference;
            Owner = owner;
            RelatedEntities = relatedEntities;
            CustomInit();
        }

        /// <summary>
        /// An initialization method that performs custom operations like setting defaults
        /// </summary>
        partial void CustomInit();

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "Values")]
        public IList<Value> Values { get; private set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "CreatedDate")]
        public System.DateTime? CreatedDate { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "CreatedBy")]
        public string CreatedBy { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "IsActive")]
        public bool? IsActive { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "Id")]
        public string Id { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "VersionDate")]
        public System.DateTime? VersionDate { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "VersionBy")]
        public string VersionBy { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "Locked")]
        public bool? Locked { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "TemplateReference")]
        public string TemplateReference { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "Owner")]
        public AssetReference Owner { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "RelatedEntities")]
        public IList<Relation> RelatedEntities { get; private set; }

    }
}
