// <auto-generated>
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace Zuuse.Lifecycle.Client.Models
{
    using Newtonsoft.Json;
    using System.Collections;
    using System.Collections.Generic;
    using System.Linq;

    public partial class InterventionSetWithTaxonomy
    {
        /// <summary>
        /// Initializes a new instance of the InterventionSetWithTaxonomy
        /// class.
        /// </summary>
        public InterventionSetWithTaxonomy()
        {
            CustomInit();
        }

        /// <summary>
        /// Initializes a new instance of the InterventionSetWithTaxonomy
        /// class.
        /// </summary>
        /// <param name="method">Possible values include: 'NotIncluded',
        /// 'Active', 'Passive', 'Reserve'</param>
        public InterventionSetWithTaxonomy(string assetId = default(string), string assetName = default(string), string method = default(string), IList<string> locationPath = default(IList<string>), IList<string> functionalPath = default(IList<string>), IList<double?> interventions = default(IList<double?>), int? availableDeferral = default(int?), IList<string> attributes = default(IList<string>), IList<double?> measures = default(IList<double?>))
        {
            AssetId = assetId;
            AssetName = assetName;
            Method = method;
            LocationPath = locationPath;
            FunctionalPath = functionalPath;
            Interventions = interventions;
            AvailableDeferral = availableDeferral;
            Attributes = attributes;
            Measures = measures;
            CustomInit();
        }

        /// <summary>
        /// An initialization method that performs custom operations like setting defaults
        /// </summary>
        partial void CustomInit();

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "AssetId")]
        public string AssetId { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "AssetName")]
        public string AssetName { get; set; }

        /// <summary>
        /// Gets or sets possible values include: 'NotIncluded', 'Active',
        /// 'Passive', 'Reserve'
        /// </summary>
        [JsonProperty(PropertyName = "Method")]
        public string Method { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "LocationPath")]
        public IList<string> LocationPath { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "FunctionalPath")]
        public IList<string> FunctionalPath { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "Interventions")]
        public IList<double?> Interventions { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "AvailableDeferral")]
        public int? AvailableDeferral { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "Attributes")]
        public IList<string> Attributes { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "Measures")]
        public IList<double?> Measures { get; set; }

    }
}
