// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License.

// <auto-generated/>

#nullable disable

using System.Collections.Generic;
using Azure.Core;

namespace Zuuse.Lifecycle.Client.Models
{
    /// <summary> The InterventionSetWithTaxonomy. </summary>
    public partial class InterventionSetWithTaxonomy
    {
        /// <summary> Initializes a new instance of InterventionSetWithTaxonomy. </summary>
        internal InterventionSetWithTaxonomy()
        {
            LocationPath = new ChangeTrackingList<string>();
            FunctionalPath = new ChangeTrackingList<string>();
            Interventions = new ChangeTrackingList<double>();
            Attributes = new ChangeTrackingList<string>();
            Measures = new ChangeTrackingList<double>();
        }

        /// <summary> Initializes a new instance of InterventionSetWithTaxonomy. </summary>
        /// <param name="assetId"> . </param>
        /// <param name="assetName"> . </param>
        /// <param name="method"> . </param>
        /// <param name="locationPath"> . </param>
        /// <param name="functionalPath"> . </param>
        /// <param name="interventions"> . </param>
        /// <param name="availableDeferral"> . </param>
        /// <param name="attributes"> . </param>
        /// <param name="measures"> . </param>
        internal InterventionSetWithTaxonomy(string assetId, string assetName, InterventionSetWithTaxonomyMethod? method, IReadOnlyList<string> locationPath, IReadOnlyList<string> functionalPath, IReadOnlyList<double> interventions, int? availableDeferral, IReadOnlyList<string> attributes, IReadOnlyList<double> measures)
        {
            AssetId = assetId;
            AssetName = assetName;
            Method = method;
            LocationPath = locationPath;
            FunctionalPath = functionalPath;
            Interventions = interventions;
            AvailableDeferral = availableDeferral;
            Attributes = attributes;
            Measures = measures;
        }

        public string AssetId { get; }
        public string AssetName { get; }
        public InterventionSetWithTaxonomyMethod? Method { get; }
        public IReadOnlyList<string> LocationPath { get; }
        public IReadOnlyList<string> FunctionalPath { get; }
        public IReadOnlyList<double> Interventions { get; }
        public int? AvailableDeferral { get; }
        public IReadOnlyList<string> Attributes { get; }
        public IReadOnlyList<double> Measures { get; }
    }
}
