// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License.

// <auto-generated/>

#nullable disable

namespace Zuuse.Lifecycle.Client.Models
{
    /// <summary> The LifecycleSettingCountByMethod. </summary>
    public partial class LifecycleSettingCountByMethod
    {
        /// <summary> Initializes a new instance of LifecycleSettingCountByMethod. </summary>
        internal LifecycleSettingCountByMethod()
        {
        }

        /// <summary> Initializes a new instance of LifecycleSettingCountByMethod. </summary>
        /// <param name="lifecycleMethodType"> . </param>
        /// <param name="count"> . </param>
        internal LifecycleSettingCountByMethod(LifecycleSettingCountByMethodLifecycleMethodType? lifecycleMethodType, int? count)
        {
            LifecycleMethodType = lifecycleMethodType;
            Count = count;
        }

        public LifecycleSettingCountByMethodLifecycleMethodType? LifecycleMethodType { get; }
        public int? Count { get; }
    }
}
