// <auto-generated>
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace Zuuse.Lifecycle.Client.Models
{
    using Newtonsoft.Json;
    using System.Linq;

    public partial class Relation
    {
        /// <summary>
        /// Initializes a new instance of the Relation class.
        /// </summary>
        public Relation()
        {
            CustomInit();
        }

        /// <summary>
        /// Initializes a new instance of the Relation class.
        /// </summary>
        /// <param name="relationship">Possible values include: 'Reference',
        /// 'EmbeddedLineItem', 'AssociatedLineItem', 'Document'</param>
        public Relation(string relationship = default(string), Entity entity = default(Entity))
        {
            Relationship = relationship;
            Entity = entity;
            CustomInit();
        }

        /// <summary>
        /// An initialization method that performs custom operations like setting defaults
        /// </summary>
        partial void CustomInit();

        /// <summary>
        /// Gets or sets possible values include: 'Reference',
        /// 'EmbeddedLineItem', 'AssociatedLineItem', 'Document'
        /// </summary>
        [JsonProperty(PropertyName = "Relationship")]
        public string Relationship { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "Entity")]
        public Entity Entity { get; set; }

    }
}
