// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License.

// <auto-generated/>

#nullable disable

namespace Zuuse.Lifecycle.Client.Models
{
    /// <summary> The Relation. </summary>
    public partial class Relation
    {
        /// <summary> Initializes a new instance of Relation. </summary>
        internal Relation()
        {
        }

        /// <summary> Initializes a new instance of Relation. </summary>
        /// <param name="relationship"> . </param>
        /// <param name="entity"> . </param>
        internal Relation(RelationRelationship? relationship, Entity entity)
        {
            Relationship = relationship;
            Entity = entity;
        }

        public RelationRelationship? Relationship { get; }
        public Entity Entity { get; }
    }
}
