// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License.

// <auto-generated/>

#nullable disable

using System;

namespace Zuuse.Lifecycle.Client.Models
{
    /// <summary> The SyncSummaryElement. </summary>
    public partial class SyncSummaryElement
    {
        /// <summary> Initializes a new instance of SyncSummaryElement. </summary>
        internal SyncSummaryElement()
        {
        }

        /// <summary> Initializes a new instance of SyncSummaryElement. </summary>
        /// <param name="id"> . </param>
        /// <param name="versionDate"> . </param>
        internal SyncSummaryElement(string id, DateTimeOffset? versionDate)
        {
            Id = id;
            VersionDate = versionDate;
        }

        public string Id { get; }
        public DateTimeOffset? VersionDate { get; }
    }
}
