// <auto-generated>
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace Zuuse.Lifecycle.Client.Models
{
    using Newtonsoft.Json;
    using System.Linq;

    public partial class SyncSummaryElement
    {
        /// <summary>
        /// Initializes a new instance of the SyncSummaryElement class.
        /// </summary>
        public SyncSummaryElement()
        {
            CustomInit();
        }

        /// <summary>
        /// Initializes a new instance of the SyncSummaryElement class.
        /// </summary>
        public SyncSummaryElement(string id = default(string), System.DateTime? versionDate = default(System.DateTime?))
        {
            Id = id;
            VersionDate = versionDate;
            CustomInit();
        }

        /// <summary>
        /// An initialization method that performs custom operations like setting defaults
        /// </summary>
        partial void CustomInit();

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "Id")]
        public string Id { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "VersionDate")]
        public System.DateTime? VersionDate { get; set; }

    }
}
