// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License.

// <auto-generated/>

#nullable disable

using System.Collections.Generic;
using Azure.Core;

namespace Zuuse.Lifecycle.Client.Models
{
    /// <summary> The TaxonomyPosition. </summary>
    public partial class TaxonomyPosition
    {
        /// <summary> Initializes a new instance of TaxonomyPosition. </summary>
        public TaxonomyPosition()
        {
            Path = new ChangeTrackingList<string>();
        }

        /// <summary> Initializes a new instance of TaxonomyPosition. </summary>
        /// <param name="id"> . </param>
        /// <param name="path"> . </param>
        /// <param name="parentId"> . </param>
        internal TaxonomyPosition(string id, IReadOnlyList<string> path, string parentId)
        {
            Id = id;
            Path = path;
            ParentId = parentId;
        }

        public string Id { get; set; }
        public IReadOnlyList<string> Path { get; }
        public string ParentId { get; set; }
    }
}
