// <auto-generated>
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace Zuuse.Lifecycle.Client.Models
{
    using Newtonsoft.Json;
    using System.Collections;
    using System.Collections.Generic;
    using System.Linq;

    public partial class TaxonomyNames
    {
        /// <summary>
        /// Initializes a new instance of the TaxonomyNames class.
        /// </summary>
        public TaxonomyNames()
        {
            CustomInit();
        }

        /// <summary>
        /// Initializes a new instance of the TaxonomyNames class.
        /// </summary>
        public TaxonomyNames(IList<string> locationTaxonomyNames = default(IList<string>), IList<string> functionalTaxonomyNames = default(IList<string>))
        {
            LocationTaxonomyNames = locationTaxonomyNames;
            FunctionalTaxonomyNames = functionalTaxonomyNames;
            CustomInit();
        }

        /// <summary>
        /// An initialization method that performs custom operations like setting defaults
        /// </summary>
        partial void CustomInit();

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "LocationTaxonomyNames")]
        public IList<string> LocationTaxonomyNames { get; private set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "FunctionalTaxonomyNames")]
        public IList<string> FunctionalTaxonomyNames { get; private set; }

    }
}
