// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License.

// <auto-generated/>

#nullable disable

using System.Collections.Generic;
using Azure.Core;

namespace Zuuse.Lifecycle.Client.Models
{
    /// <summary> The TaxonomySummary. </summary>
    public partial class TaxonomySummary
    {
        /// <summary> Initializes a new instance of TaxonomySummary. </summary>
        internal TaxonomySummary()
        {
            Interventions = new ChangeTrackingList<double>();
        }

        /// <summary> Initializes a new instance of TaxonomySummary. </summary>
        /// <param name="id"> . </param>
        /// <param name="name"> . </param>
        /// <param name="isPhysical"> . </param>
        /// <param name="interventions"> . </param>
        internal TaxonomySummary(string id, string name, bool? isPhysical, IReadOnlyList<double> interventions)
        {
            Id = id;
            Name = name;
            IsPhysical = isPhysical;
            Interventions = interventions;
        }

        public string Id { get; }
        public string Name { get; }
        public bool? IsPhysical { get; }
        public IReadOnlyList<double> Interventions { get; }
    }
}
