// <auto-generated>
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace Zuuse.Lifecycle.Client.Models
{
    using Newtonsoft.Json;
    using System.Collections;
    using System.Collections.Generic;
    using System.Linq;

    public partial class TaxonomyPosition
    {
        /// <summary>
        /// Initializes a new instance of the TaxonomyPosition class.
        /// </summary>
        public TaxonomyPosition()
        {
            CustomInit();
        }

        /// <summary>
        /// Initializes a new instance of the TaxonomyPosition class.
        /// </summary>
        public TaxonomyPosition(string id = default(string), IList<string> path = default(IList<string>), string parentId = default(string))
        {
            Id = id;
            Path = path;
            ParentId = parentId;
            CustomInit();
        }

        /// <summary>
        /// An initialization method that performs custom operations like setting defaults
        /// </summary>
        partial void CustomInit();

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "Id")]
        public string Id { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "Path")]
        public IList<string> Path { get; private set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "ParentId")]
        public string ParentId { get; set; }

    }
}
