// <auto-generated>
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace Zuuse.Lifecycle.Client.Models
{
    using Newtonsoft.Json;
    using System.Linq;

    public partial class Value
    {
        /// <summary>
        /// Initializes a new instance of the Value class.
        /// </summary>
        public Value()
        {
            CustomInit();
        }

        /// <summary>
        /// Initializes a new instance of the Value class.
        /// </summary>
        public Value(string fieldName = default(string), string stringValue = default(string))
        {
            FieldName = fieldName;
            StringValue = stringValue;
            CustomInit();
        }

        /// <summary>
        /// An initialization method that performs custom operations like setting defaults
        /// </summary>
        partial void CustomInit();

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "FieldName")]
        public string FieldName { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "StringValue")]
        public string StringValue { get; set; }

    }
}
