// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License.

// <auto-generated/>

#nullable disable

namespace Zuuse.Lifecycle.Client.Models
{
    /// <summary> The Value. </summary>
    public partial class Value
    {
        /// <summary> Initializes a new instance of Value. </summary>
        internal Value()
        {
        }

        /// <summary> Initializes a new instance of Value. </summary>
        /// <param name="fieldName"> . </param>
        /// <param name="stringValue"> . </param>
        internal Value(string fieldName, string stringValue)
        {
            FieldName = fieldName;
            StringValue = stringValue;
        }

        public string FieldName { get; }
        public string StringValue { get; }
    }
}
