// <auto-generated>
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace Zuuse.Lifecycle.Client
{
    using Models;
    using Newtonsoft.Json;

    /// <summary>
    /// </summary>
    public partial interface IZuuseLifecycleManagementApi : System.IDisposable
    {
        /// <summary>
        /// The base URI of the service.
        /// </summary>
        System.Uri BaseUri { get; set; }

        /// <summary>
        /// Gets or sets json serialization settings.
        /// </summary>
        JsonSerializerSettings SerializationSettings { get; }

        /// <summary>
        /// Gets or sets json deserialization settings.
        /// </summary>
        JsonSerializerSettings DeserializationSettings { get; }


        /// <summary>
        /// Gets the IBaselineOperations.
        /// </summary>
        IBaselineOperations Baseline { get; }

        /// <summary>
        /// Gets the ILifecycle.
        /// </summary>
        ILifecycle Lifecycle { get; }

        /// <summary>
        /// Gets the IScenario.
        /// </summary>
        IScenario Scenario { get; }

        /// <summary>
        /// Gets the IZuuse.
        /// </summary>
        IZuuse Zuuse { get; }

    }
}
